# Generated by Django 3.0.8 on 2020-08-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200809_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followed',
            name='followeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='followers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerrrs', to=settings.AUTH_USER_MODEL),
        ),
    ]
